<a href="https://colab.research.google.com/github/Priyankamadineni999/ML_Algorithms/blob/main/Logistic_Reg_Al.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
from sklearn.linear_model import LogisticRegression

In [3]:
df_diabete=pd.read_csv('diabete.csv')

In [4]:
df_diabete.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [7]:
#checking null values
df_diabete.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [12]:
#drop unneccessary columns
df_diabete.drop(columns=["Age","Insulin","SkinThickness"],axis=1,inplace=True)

KeyError: ignored

In [10]:
df_diabete

Pregnancies  Glucose  BloodPressure   BMI  DiabetesPedigreeFunction  \
0              6      148             72  33.6                     0.627   
1              1       85             66  26.6                     0.351   
2              8      183             64  23.3                     0.672   
3              1       89             66  28.1                     0.167   
4              0      137             40  43.1                     2.288   
..           ...      ...            ...   ...                       ...   
763           10      101             76  32.9                     0.171   
764            2      122             70  36.8                     0.340   
765            5      121             72  26.2                     0.245   
766            1      126             60  30.1                     0.349   
767            1       93             70  30.4                     0.315   

     Outcome  
0          1  
1          0  
2          1  
3          0  
4          1  
..       ...  
763        0  
764        0  
765        0  
766        1  
767        0  

[768 rows x 6 columns]

In [13]:
df_diabete.drop(columns=["BMI"],axis=1,inplace=True)

In [14]:
df_diabete

Pregnancies  Glucose  BloodPressure  DiabetesPedigreeFunction  Outcome
0              6      148             72                     0.627        1
1              1       85             66                     0.351        0
2              8      183             64                     0.672        1
3              1       89             66                     0.167        0
4              0      137             40                     2.288        1
..           ...      ...            ...                       ...      ...
763           10      101             76                     0.171        0
764            2      122             70                     0.340        0
765            5      121             72                     0.245        0
766            1      126             60                     0.349        1
767            1       93             70                     0.315        0

[768 rows x 5 columns]

In [15]:
df_diabete.drop(columns=["Pregnancies"],axis=1,inplace=True)

In [16]:
df_diabete.head()


Glucose  BloodPressure  DiabetesPedigreeFunction  Outcome
0      148             72                     0.627        1
1       85             66                     0.351        0
2      183             64                     0.672        1
3       89             66                     0.167        0
4      137             40                     2.288        1

In [18]:
#creating independent and dependent features
x=df_diabete.iloc[:,:-1]
y=df_diabete.iloc[:,-1]


In [19]:
x

Glucose  BloodPressure  DiabetesPedigreeFunction
0        148             72                     0.627
1         85             66                     0.351
2        183             64                     0.672
3         89             66                     0.167
4        137             40                     2.288
..       ...            ...                       ...
763      101             76                     0.171
764      122             70                     0.340
765      121             72                     0.245
766      126             60                     0.349
767       93             70                     0.315

[768 rows x 3 columns]

In [21]:
#training testing spliting data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=0)

In [22]:
x_train.shape

(537, 3)

In [23]:
#Feature scalling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)

In [24]:
x_train

array([[ 0.9144385 ,  1.04559346, -0.3002719 ],
       [-1.19655127, -0.08570438,  0.45699051],
       [ 0.01416345,  0.01714088, -0.39305899],
       ...,
       [-0.85506763, -0.23997227, -0.96774035],
       [-1.13446334,  0.22283139, -0.51278428],
       [ 0.44877899,  0.63421243,  0.50488062]])

In [26]:
#training the model
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

LogisticRegression(random_state=0)

In [27]:
#testing the model
#predicting the test model
y_pred=classifier.predict(x_test)

In [28]:
y_pred

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0])

In [38]:
#confusion matrics accuracy
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[136  21]
 [ 37  37]]


0.7489177489177489

In [39]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.87      0.82       157
           1       0.64      0.50      0.56        74

    accuracy                           0.75       231
   macro avg       0.71      0.68      0.69       231
weighted avg       0.74      0.75      0.74       231

